"""Case insensitive email index

Revision ID: 97231e0858ff
Revises: 9889e81c8aa4
Create Date: 2026-07-14 18:47:51.551871
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97231e0858ff"
down_revision: str | None = "9889e81c8aa4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email", table_name="users")
    op.create_index(
        "ix_users_email_lower", "users", [sa.text("lower(email)")], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email_lower", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###
