"""replace prompt_file_url with prompt_text

Revision ID: d9fef4b110fd
Revises: 557cc50ec443
Create Date: 2026-07-15 15:16:25.528155
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'd9fef4b110fd'
down_revision: Union[str, None] = '557cc50ec443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('prompt_text', sa.Text(), nullable=True))
    op.drop_column('prompts', 'prompt_file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('prompt_file_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True))
    op.drop_column('prompts', 'prompt_text')
    # ### end Alembic commands ###
